"""Shared v2 router pipeline, mirroring 05_router_pretreatment.ipynb.

This module re-implements the notebook's reduced-leakage (v2) pipeline as
importable functions so that experiment scripts (06_experiments.py) reuse the
exact same data, split, features, model, and cell estimator. Running this file
directly reprints the headline numbers as a reproduction gate:

    test MAE 0.306 (title+repo), 0.309 (repo-only);
    success-only routing: Always-Codex 0.880, Instance 0.876, Cell-argmax 0.862.
"""
import os
import re
from types import SimpleNamespace

import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import mean_absolute_error
import xgboost as xgb

DATA_PATH = "data/router_dataset.jsonl"
AGENTS = ["OpenAI_Codex", "Copilot", "Devin", "Cursor", "Claude_Code"]
SUCCESS_MAP = {"merged": 1.0, "still_open": 0.3, "closed_unmerged": 0.0}
RANDOM_STATE = 42
EMB_MODEL = "all-MiniLM-L6-v2"
COST = {"Copilot": 1.10, "OpenAI_Codex": 3.85, "Cursor": 3.85, "Claude_Code": 4.80, "Devin": 4.50}
NUM = ["log_stars", "log_forks", "has_issue_i"]  # no body-derived (post-treatment) features

_AGENT_TOK = re.compile(r"\b(copilot|devin|cursor|codex|claude|openai|anthropic)\b", re.I)
_FOOT = re.compile(r"generated with|generated by|co-authored-by|\U0001f916", re.I)


def clean_title(t):
    t = _FOOT.sub(" ", str(t))
    t = _AGENT_TOK.sub(" ", t)
    return re.sub(r"\s+", " ", t).strip()


def load_df(success_map=SUCCESS_MAP):
    """Load the corpus, derive success target, cleaned title, and numeric features."""
    df = pd.read_json(DATA_PATH, lines=True).reset_index(drop=True)
    df["success"] = df["outcome"].map(success_map)
    df["title_clean"] = df["title"].map(clean_title)
    df["log_stars"] = np.log1p(df["stars"])
    df["log_forks"] = np.log1p(df["forks"])
    df["has_issue_i"] = df["has_issue"].astype(int)
    return df


def split_df(df):
    def gsplit(d, ts):
        a, b = next(GroupShuffleSplit(1, test_size=ts, random_state=RANDOM_STATE).split(d, groups=d["repo_id"]))
        return d.iloc[a].copy(), d.iloc[b].copy()
    train_df, temp = gsplit(df, 0.30)
    val_df, test_df = gsplit(temp, 0.50)
    assert not (set(train_df.repo_id) & set(test_df.repo_id))
    return train_df, val_df, test_df


def load_emb(df, model_name=EMB_MODEL):
    """Frozen sentence-embedding of the cleaned title; reads the cached .npy if present."""
    safe = model_name.replace("/", "_")
    cache = f"data/emb_title_{safe}_{len(df)}.npy"
    if os.path.exists(cache):
        return np.load(cache)
    import torch
    from sentence_transformers import SentenceTransformer
    dev = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
    m = SentenceTransformer(model_name, device=dev)
    texts = df["title_clean"].tolist()
    e = m.encode([t if str(t).strip() else " " for t in texts], batch_size=256,
                 show_progress_bar=True, normalize_embeddings=True)
    np.save(cache, e)
    return e


def build_encoders(train_df):
    lang_oh = OneHotEncoder(handle_unknown="infrequent_if_exist", min_frequency=50,
                            sparse_output=False).fit(train_df[["language"]])
    task_oh = OneHotEncoder(handle_unknown="ignore", sparse_output=False).fit(train_df[["task_type"]])
    agent_oh = OneHotEncoder(categories=[AGENTS], handle_unknown="ignore",
                             sparse_output=False).fit(train_df[["agent"]])
    return lang_oh, task_oh, agent_oh


def base_features(d, txt, enc, with_text=True):
    lang_oh, task_oh, _ = enc
    blocks = [d[NUM].to_numpy(float), lang_oh.transform(d[["language"]]), task_oh.transform(d[["task_type"]])]
    if with_text:
        blocks = [txt] + blocks
    return np.hstack(blocks)


def with_agent(b, ags, agent_oh):
    return np.hstack([b, agent_oh.transform(pd.DataFrame({"agent": ags}))])


def feature_names(enc, emb_dim, with_text=True):
    lang_oh, task_oh, agent_oh = enc
    names = []
    if with_text:
        names += [f"emb_{i:03d}" for i in range(emb_dim)]
    names += list(NUM)
    names += list(lang_oh.get_feature_names_out(["language"]))
    names += list(task_oh.get_feature_names_out(["task_type"]))
    names += list(agent_oh.get_feature_names_out(["agent"]))
    return names


def fit_xgb(Xtr, ytr, Xva, yva):
    m = xgb.XGBRegressor(n_estimators=800, learning_rate=0.05, max_depth=6, subsample=0.8,
                         colsample_bytree=0.8, min_child_weight=5, reg_lambda=1.0,
                         early_stopping_rounds=40, random_state=RANDOM_STATE, n_jobs=-1)
    m.fit(Xtr, ytr, eval_set=[(Xva, yva)], verbose=False)
    return m


def make_cell_estimator(train_df, val_df, test_df):
    """Direct-method estimator: route by TRAIN cells, value choices on VAL cells."""
    TOPL = set(train_df.language.value_counts().head(12).index)

    def cell_of(d):
        lang = d.language.where(d.language.isin(TOPL), "Other")
        return (lang + "|" + d.task_type).values

    for d in (train_df, val_df, test_df):
        d["cell"] = cell_of(d)

    def qtab(d):
        gm = d.groupby("agent").success.mean()
        q = d.groupby(["cell", "agent"]).success.mean().unstack().reindex(columns=AGENTS)
        for a in AGENTS:
            q[a] = q[a].fillna(gm[a])
        return q, gm

    q_tr, gm_tr = qtab(train_df)
    q_va, gm_va = qtab(val_df)
    tc = test_df.cell.values

    def Q(tab, gm, agents):
        return np.array([tab.loc[c, a] if c in tab.index else gm[a] for c, a in zip(tc, np.asarray(agents))])

    def pval(choice):
        return float(Q(q_va, gm_va, np.asarray(choice)).mean())

    def mcost(choice):
        return float(np.mean([COST[a] for a in choice]))

    return SimpleNamespace(q_tr=q_tr, gm_tr=gm_tr, q_va=q_va, gm_va=gm_va, tc=tc,
                           Q=Q, pval=pval, mcost=mcost)


def prepare(success_map=SUCCESS_MAP, with_text=True):
    """Build the full v2 pipeline once and return everything experiments need."""
    df = load_df(success_map)
    train_df, val_df, test_df = split_df(df)
    emb = load_emb(df)
    txt_tr = emb[train_df.index.values]
    txt_va = emb[val_df.index.values]
    txt_te = emb[test_df.index.values]
    enc = build_encoders(train_df)
    _, _, agent_oh = enc

    bt = base_features(train_df, txt_tr, enc, with_text)
    bv = base_features(val_df, txt_va, enc, with_text)
    bte = base_features(test_df, txt_te, enc, with_text)
    Xtr, ytr = with_agent(bt, train_df.agent, agent_oh), train_df.success.to_numpy()
    Xva, yva = with_agent(bv, val_df.agent, agent_oh), val_df.success.to_numpy()
    Xte, yte = with_agent(bte, test_df.agent, agent_oh), test_df.success.to_numpy()

    model = fit_xgb(Xtr, ytr, Xva, yva)
    scores = pd.DataFrame({a: model.predict(with_agent(bte, [a] * len(bte), agent_oh)) for a in AGENTS},
                          index=test_df.index)
    est = make_cell_estimator(train_df, val_df, test_df)

    return SimpleNamespace(
        df=df, train_df=train_df, val_df=val_df, test_df=test_df,
        emb=emb, txt_tr=txt_tr, txt_va=txt_va, txt_te=txt_te, enc=enc, agent_oh=agent_oh,
        bt=bt, bv=bv, bte=bte, Xtr=Xtr, ytr=ytr, Xva=Xva, yva=yva, Xte=Xte, yte=yte,
        model=model, scores=scores, est=est,
        feature_names=feature_names(enc, emb.shape[1], with_text),
    )


if __name__ == "__main__":
    p = prepare()
    amean = p.train_df.groupby("agent").success.mean()
    mae_base = mean_absolute_error(p.yte, p.test_df.agent.map(amean))
    mae_v2 = mean_absolute_error(p.yte, p.model.predict(p.Xte))

    # repo-only (no text) ablation
    bt2 = base_features(p.train_df, None, p.enc, with_text=False)
    bv2 = base_features(p.val_df, None, p.enc, with_text=False)
    bte2 = base_features(p.test_df, None, p.enc, with_text=False)
    m2 = fit_xgb(with_agent(bt2, p.train_df.agent, p.agent_oh), p.ytr,
                 with_agent(bv2, p.val_df.agent, p.agent_oh), p.yva)
    mae_repo = mean_absolute_error(p.yte, m2.predict(with_agent(bte2, p.test_df.agent, p.agent_oh)))

    inst = p.scores[AGENTS].idxmax(1).values
    cell_best = p.est.q_tr.idxmax(1)
    cell_argmax = [cell_best.get(c, p.est.gm_tr.idxmax()) for c in p.est.tc]
    codex = ["OpenAI_Codex"] * len(p.test_df)

    print("== reproduction gate (compare to report) ==")
    print(f"per-agent-mean baseline MAE   {mae_base:.3f}  (report 0.331)")
    print(f"v2 (title+repo) MAE           {mae_v2:.3f}  (report 0.306)")
    print(f"v2 (repo-only) MAE            {mae_repo:.3f}  (report 0.309)")
    print(f"Always-Codex   success        {p.est.pval(codex):.3f}  (report 0.880)")
    print(f"Instance router success       {p.est.pval(inst):.3f}  (report 0.876)")
    print(f"Cell-argmax    success        {p.est.pval(cell_argmax):.3f}  (report 0.862)")
